Department.find_or_create_by(name: 'Sales')
Department.find_or_create_by(name: 'Marketing')
Department.find_or_create_by(name: 'Finance')
Department.find_or_create_by(name: 'Human Resources')
Department.find_or_create_by(name: 'Information Technology')